"""CI/CD テンプレート生成 — redteam-scan --init-ci"""
from __future__ import annotations

from pathlib import Path

_GITHUB_ACTIONS_TEMPLATE = """\
# AI Red Teaming Engine — GitHub Actions CI
# Generated by: redteam-scan --init-ci
#
# このワークフローは Pull Request 時に自動でセキュリティ監査を実行します。
# - Critical 指摘が1件でもあればビルドを失敗させます
# - SARIF を GitHub Security Tab にアップロードします
# - HTML レポートを artifact として保存します
#
# 必要な設定:
#   1. ANTHROPIC_API_KEY を GitHub Secrets に追加してください
#   2. (任意) .redteam-ignore で除外パスを設定できます
#   3. (任意) .redteam-rules.yaml でカスタムルールを追加できます

name: AI Red Team Scan

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  workflow_dispatch:  # 手動実行も可能

permissions:
  contents: read
  security-events: write   # GitHub Security Tab へのアップロードに必要
  actions: read

jobs:
  redteam-scan:
    name: Security Audit
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install AI Red Teaming Engine
        run: pip install "ai-red-teaming-engine[all]"

      - name: Install semgrep (静的解析)
        run: pip install semgrep

      - name: Run AI Red Team Scan
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          redteam-scan \\
            --dir . \\
            --mode deep \\
            --format sarif \\
            --output redteam-results.sarif \\
            --fail-on Critical \\
            --no-save-log \\
            --preset balanced
        continue-on-error: true  # SARIF/HTML を必ず生成するため

      - name: Generate HTML Report
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          redteam-scan \\
            --dir . \\
            --mode deep \\
            --format html \\
            --output redteam-report.html \\
            --no-save-log \\
            --preset balanced
        continue-on-error: true

      - name: Upload SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: redteam-results.sarif
          category: ai-red-teaming

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: redteam-report-${{ github.run_number }}
          path: redteam-report.html
          retention-days: 30

      - name: Fail on Critical findings
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          redteam-scan \\
            --dir . \\
            --mode deep \\
            --no-save-log \\
            --preset balanced \\
            --fail-on Critical
"""

_GITLAB_CI_TEMPLATE = """\
# AI Red Teaming Engine — GitLab CI
# Generated by: redteam-scan --init-ci --platform gitlab

stages:
  - security

redteam-scan:
  stage: security
  image: python:3.12-slim
  before_script:
    - pip install "ai-red-teaming-engine[all]" semgrep
  script:
    - redteam-scan
        --dir .
        --mode deep
        --format sarif
        --output redteam-results.sarif
        --fail-on Critical
        --no-save-log
        --preset balanced
    - redteam-scan
        --dir .
        --mode deep
        --format html
        --output redteam-report.html
        --no-save-log
        --preset balanced
  artifacts:
    reports:
      sast: redteam-results.sarif
    paths:
      - redteam-report.html
    expire_in: 30 days
  variables:
    ANTHROPIC_API_KEY: $ANTHROPIC_API_KEY
  only:
    - merge_requests
    - main
    - master
"""

_REDTEAM_IGNORE_TEMPLATE = """\
# .redteam-ignore — AI Red Teaming Engine 除外設定
# 書式: glob パターン (fnmatch 準拠)

# テスト・フィクスチャ（誤検知が多いため除外）
tests/
test_*/
*_test.py
conftest.py
fixtures/

# ビルド成果物
dist/
build/
*.egg-info/
__pycache__/
.pytest_cache/
node_modules/

# ドキュメント・設定
*.md
*.yml
*.yaml
*.toml
*.cfg
*.ini
*.lock
"""

_PLATFORMS = {
    "github": ("github", ".github/workflows/redteam.yml", _GITHUB_ACTIONS_TEMPLATE),
    "gitlab": ("gitlab", ".gitlab-ci.yml", _GITLAB_CI_TEMPLATE),
}


def init_ci(
    platform: str = "github",
    output_dir: str = ".",
    force: bool = False,
) -> list[str]:
    """
    CI テンプレートを生成して書き出す。

    Returns:
        生成したファイルパスのリスト
    """
    root = Path(output_dir)
    created: list[str] = []

    if platform not in _PLATFORMS:
        raise ValueError(f"未対応のプラットフォーム: {platform!r}。対応: {list(_PLATFORMS)}")

    _, wf_path, wf_content = _PLATFORMS[platform]
    target = root / wf_path
    target.parent.mkdir(parents=True, exist_ok=True)

    if target.exists() and not force:
        raise FileExistsError(
            f"{target} は既に存在します。上書きするには --force を指定してください。"
        )
    target.write_text(wf_content, encoding="utf-8")
    created.append(str(target))

    ignore_path = root / ".redteam-ignore"
    if not ignore_path.exists():
        ignore_path.write_text(_REDTEAM_IGNORE_TEMPLATE, encoding="utf-8")
        created.append(str(ignore_path))

    return created
